# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup do NodeJS
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.13.2

      - name: Instalação do Mocha e pacotes para teste
        run: |
          cd 1_primeiro_exemplo/src;
          npm install -g mocha;
          npm install

      - name: Execução do teste
        run: mocha 1_primeiro_exemplo/src/test/convert.js
        
      - name: Autenticação do Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        

      - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
        uses: docker/build-push-action@v2.9.0
        with:
          context: ./1_primeiro_exemplo/src
          file: ./1_primeiro_exemplo/src/Dockerfile
          push: true
          tags: |
            jessikamorais/conversao-temperatura:v1
            jessikamorais/conversao-temperatura:latest
        

    

